scss_files: '*.scss'


exclude:
  - 'test.scss'


linters:
  BangFormat:
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    convention: none

  DebugStatement:
    severity: warning

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    style: same_line

  EmptyLineBetweenBlocks:
    severity: warning
    ignore_single_line_blocks: true

  EmptyRule:
    severity: warning

  HexLength:
    severity: warning
    style: short

  HexNotation:
    severity: warning
    style: uppercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  ImportPath:
    severity: warning
    leading_underscore: false
    filename_extension: false

  Indentation:
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    severity: warning
    style: include_zero

  MergeableSelector:
    severity: warning
    force_nesting: true

  NameFormat:
    severity: warning

  PropertySpelling:
    enabled: true

  PropertySortOrder:
    ignore_unspecified: true
    order:
      - appearance
      - content
      - src
      -
      - display
      - position
      - float
      -
      - z-index
      -
      - size
      - width
      - height
      - min-width
      - max-width
      - min-height
      - max-height
      -
      - top
      - bottom
      - left
      - right
      -
      - margin
      - margin-top
      - margin-bottom
      - margin-left
      - margin-right
      - margin-collapse
      - margin-top-collapse
      - margin-bottom-collapse
      - margin-left-collapse
      - margin-right-collapse
      - padding
      - padding-top
      - padding-bottom
      - padding-left
      - padding-right
      -
      - cursor
      - pointer-events
      - user-select
      -
      - list-style
      - list-style-type
      - list-style-position
      - list-style-image
      -
      - opacity
      - filter
      - visibility
      - backface-visibility
      -
      - background
      - background-attachment
      - background-clip
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-repeat-x
      - background-repeat-y
      - background-size
      -
      - border
      - border-color
      - border-style
      - border-width
      - border-top
      - border-top-color
      - border-top-style
      - border-top-width
      - border-bottom
      - border-bottom-color
      - border-bottom-style
      - border-bottom-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-collapse
      - border-spacing
      - border-radius
      - border-radius-topleft
      - border-radius-topright
      - border-radius-bottomleft
      - border-radius-bottomright
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      -
      - box-align
      - box-flex
      - box-orient
      - box-pack
      - box-shadow
      - box-sizing
      -
      - animation
      - animation-delay
      - animation-duration
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - animation-fill-mode
      -
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      -
      - direction
      - resize
      -
      - color
      - font
      - font-family
      - font-size
      - font-smoothing
      - osx-font-smoothing
      - font-style
      - font-weight
      -
      - vertical-align
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-size-adjust
      - text-shadow
      - text-transform
      -
      - line-height
      - letter-spacing
      - word-spacing
      -
      - outline
      - outline-offset
      -
      - table-layout
      -
      - transform
      - zoom
      -
      - clip
      - clear
      - hyphens
      - marks
      - quotes
      - word-break
      - word-wrap
      - white-space
      - page
      - interpolation-mode
      - set-link-source
      - unicode-bidi
      - speak

  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorFormat:
    severity: warning
    attribute_convention: camel_case
    class_convention: hyphenated_lowercase
    id_convention: camel_case

  Shorthand:
    severity: warning

  SingleLinePerProperty:
    severity: warning
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: false

  SpaceAfterPropertyColon:
    severity: warning
    style: at_least_one_space

  SpaceAfterPropertyName:
    severity: warning

  SpaceBeforeBrace:
    severity: warning
    allow_single_line_padding: true
    style: space

  SpaceBetweenParens:
    severity: warning
    spaces: 0

  StringQuotes:
    severity: warning
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  UnnecessaryParentReference:
    severity: warning

  UrlQuotes:
    severity: warning

  VendorPrefix:
    enabled: false

  ZeroUnit:
    severity: warning
